name = "HyperRF"
uuid = "95cc262a-bdd0-4e85-9492-52b7d586f8d9"
authors = ["Ali Bagci"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
